name: Build

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        uses: docker://morphy/revive-action:v2
        with:
          config: "./revive.toml"
          path: "./..."

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest

    services:
      secure:
        image: azazeal/vasctest:latest
        ports:
          - 10000

      insecure:
        image: azazeal/vasctest:latest
        env:
          INSECURE: true
        ports:
          - 10000

    strategy:
      matrix:
        go: ['1.17', '1.18']

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -race -coverpkg=./... -coverprofile=coverage.cov -covermode=atomic ./...
      env:
        SECURE_HOST: localhost:${{ job.services.secure.ports[10000] }}
        SECRET: supersecret
        INSECURE_HOST: localhost:${{ job.services.insecure.ports[10000] }}
    - name: Start uploading coverage report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.cov
        flag-name: go${{ matrix.go }}
        parallel: true

  finalize:
    name: Finalize
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Finish uploading coverage reports
        uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
