name: Build Package

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    name: Call Lint
    uses: azazeal/workflows/.github/workflows/golint.yml@master

  test:
    needs: call-lint
    name: Test
    runs-on: ubuntu-latest
    services:
      secure:
        image: azazeal/vasctest:latest
        ports:
          - 10000
        options: >-
          --health-cmd "nc -z localhost 10000"
          --health-interval 1s
          --health-timeout 1s
          --health-retries 10
          --health-start-period 5s

      insecure:
        image: azazeal/vasctest:latest
        env:
          INSECURE: true
        ports:
          - 10000
        options: >-
          --health-cmd "nc -z localhost 10000"
          --health-interval 1s
          --health-timeout 1s
          --health-retries 10
          --health-start-period 5s

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        check-latest: true
    - name: Install gotestsum
      run: |
        go install gotest.tools/gotestsum@v1
    - name: Run Test Suite
      run: |
        gotestsum -- -race -coverpkg=./... -coverprofile=coverprofile -covermode=atomic ./...
      env:
        GOTESTSUM_JSONFILE: gotestsum.json
        SECURE_HOST: localhost:${{ job.services.secure.ports[10000] }}
        SECRET: supersecret
        INSECURE_HOST: localhost:${{ job.services.insecure.ports[10000] }}
    - name: Annotate Test Suite Results
      if: ${{ (success() || failure()) && hashFiles('gotestsum.json') != '' }}
      uses: guyarb/golang-test-annotations@v0.6.0
      with:
        test-results: gotestsum.json
    - name: Start Uploading Coverage Report
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverprofile

