name: Build

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        uses: docker://morphy/revive-action:v2
        with:
          config: "./revive.toml"
          path: "./..."

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16', '1.17']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create artifacts directory
      run: |
        rm -rf artifacts
        mkdir artifacts
    - name: Setup
      env:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: docker-compose build --pull --build-arg GO=${{ matrix.go }}
    - name: Run tests
      run: docker-compose run --rm vasc
    - name: Upload coverage report
      if: ${{ matrix.go == '1.17' }}
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: artifacts/coverage.out
    - name: Teardown
      run: docker-compose rm -v --stop --force
